### ISSUE TITLE
unknown error

### ISSUE THREAD

**Issue by frankbioinfo** [Xinglab/rmats2sashimiplot#21] opened 2017-12-04 17:03 UTC
hi rmats team, @ShiehShieh @bahramis 

Thank you for developing this tool. 

I see this error when I try to plot using only co ordinate and gff3 file. 

"list index out of range
There is an exception in plot_with_coordinate"

Thanks 
Frank.

**Comment by sridhar0605** [comment] 2017-12-04 21:07
@ShiehShieh  could you please help with this issue

**Comment by ShiehShieh** [comment] 2017-12-04 21:09
Hi @frankbioinfo ,

Could you send me the complete error message and your command line input?

Thanks

**Comment by frankbioinfo** [comment] 2017-12-04 21:13
here is the command i used @ShiehShieh 
rmats2sashimiplot$ python rmats2sashimiplot.py --b1 mutant_1.bam, mutant_2.bam, mutant_3.bam --b2 control_1.bam, control_2.bam, control_3 .bam--l1 mutant --l2 control -o trial_out/ -c 10:-:77649470:77707387:mm9.gff3

'mutant_1.bam' seems to be indexed already. Please Check out this index file 'mutant_1.bam.bai'
'mutant_2.bam' seems to be indexed already. Please Check out this index file 'mutant_2.bam.bai'
'mutant_3.bam' seems to be indexed already. Please Check out this index file 'mutant_3.bam.bai'
'control_1.bam' seems to be indexed already. Please Check out this index file 'control_1.bam.bai'
'control_2.bam' seems to be indexed already. Please Check out this index file 'control_2.bam.bai'
'control_3.bam' seems to be indexed already. Please Check out this index file 'control_3.bam.bai'

list index out of range
There is an exception in plot_with_coordinate

**Comment by frankbioinfo** [comment] 2017-12-04 21:54
Please let me know if you need any additional information @ShiehShieh

**Comment by ShiehShieh** [comment] 2017-12-04 21:55
I've located the issue. Trying to fix that. Will let you know when new commit available. @frankbioinfo

**Comment by frankbioinfo** [comment] 2017-12-04 21:56
Thank you, appreciate it @ShiehShieh

**Comment by ShiehShieh** [comment] 2017-12-04 22:30
I just updated the repo. Please try to run the new program. @frankbioinfo

**Comment by frankbioinfo** [comment] 2017-12-04 22:41
I still get the same error, i git cloned from the master

**Comment by frankbioinfo** [comment] 2017-12-04 23:36
I get this error @ShiehShieh after pulling the new commit
Plotting read densities and MISO estimates along event...
  - Event: chr10:77649470:77707388:-
Setting up plot using dimensions:  [8.0, 7.0]
Using intron scale  5.0
Using exon scale  1.0
Reading sample label: mutant-1
Error retrieving files from chr10: invalid contig `chr10`
Are you sure chr10 appears in your BAM file?
Aborting plot...
Traceback (most recent call last):


I guess i have ensembl bams with out the chr prefix

**Comment by frankbioinfo** [comment] 2017-12-05 01:06
Hi @ShiehShieh  i poked around the code and remove the chr condition 

if not in_chr.startswith("chr"):  # add 'chr' prefix to the sequence name which is from the input arguement
            in_chr = "chr" + in_chr
        in_strand = tmp_str[1]
        in_coor_s = tmp_str[2]
        in_coor_e = int(tmp_str[3]) + 1
        id_str = in_chr + ":" + in_coor_s + ":" + str(in_coor_e) + ":" + in_strand  # chr2:10101175:10104171:+
        gff3_file = tmp_str[4]
        fo = open(gff3_file, 'r')
        w2 = open(os.path.join(options.sashimi_path, "SE.event.list.txt"), 'w')
        w1 = open(os.path.join(options.sashimi_path, "tmp.gff3"), 'w')

        w1.write("%s\tensGene\tgene\t%s\t%s\t.\t%s\t.\tID=%s;Name=%s\n" %
                 (in_chr, in_coor_s, in_coor_e, in_strand, id_str, id_str))
        # w1.write("%s\tensGene\tmRNA\t%s\t%s\t.\t%s\t.\tName=ENST00000000000;Parent=%s;ID=ENST00000000000\n" %
        #          (in_chr, in_coor_s, in_coor_e, in_strand, id_str))

        events_no = 0
        for line in fo:
            if line.startswith('#'):
                continue
            events_no += 1
            items = line.split("\t")
            if items[0].startswith("chr"):
                item_chr = items[0]



My plot looks like this i don't know whats wrong 
<img width="596" alt="screen shot 2017-12-04 at 7 03 52 pm" src="https://user-images.githubusercontent.com/27443838/33584697-283c017a-d926-11e7-8d73-eae2f387934c.png">

**Comment by ShiehShieh** [comment] 2017-12-07 22:39
Did you mean you commented out:

`

        if not in_chr.startswith("chr"): # add 'chr' prefix to the sequence name which is from the input arguement

        in_chr = "chr" + in_chr
`

and

change
`

            if items[0].startswith("chr"):
                item_chr = items[0]

            else:  # add 'chr' prefix to the seqence name which is from the gff3 file
                item_chr = "chr" + items[0]
`

to

`

            item_chr = items[0]
`

I just pushed another commit included changes above. For now, I remove the 'chr' condition, and it's recommend that you check that your BAM files follow the same headers naming convention as your GFF.

**Comment by kapilaGIT** [comment] 2019-06-20 06:54
Hi,

I have got the same error reported here even when I use new version of the tool.

python /usr/local/rmats2sashimiplot-2.0.3/src/rmats2sashimiplot/rmats2sashimiplot.py --b1 /mnt/vde/ming_totalRNASeq/20181025.A-siControl_Tal_1_R1Aligned.sortedByCoord.out.bam,/mnt/vde/ming_totalRNASeq/20181025.A-siControl_Tal_2_R1Aligned.sortedByCoord.out.bam,/mnt/vde/ming_totalRNASeq/20181025.A-siControl_Tal_3_R1Aligned.sortedByCoord.out.bam --b2 /mnt/vde/ming_totalRNASeq/20181025.A-siControl_DMSO_1_R1Aligned.sortedByCoord.out.bam,/mnt/vde/ming_totalRNASeq/20181025.A-siControl_DMSO_2_R1Aligned.sortedByCoord.out.bam,/mnt/vde/ming_totalRNASeq/20181025.A-siControl_DMSO_3_R1Aligned.sortedByCoord.out.bam --l1 siControl_TAL --l2 siControl_DMSO --exon_s 1 --intron_s 1 -o siControl_TAL.vs.siControl_DMSO_plots_test -t RI -e siControl_TAL.vs.siControl_DMSO/fromGTF.novelEvents.RI.txt -c 10:-:77649470:77707387:/mnt/vde/ming_totalRNASeq/Mus_musculus/UCSC/mm10/Annotation/Genes/genes.gff

'/mnt/vde/ming_totalRNASeq/20181025.A-siControl_Tal_1_R1Aligned.sortedByCoord.out.bam' seems to be indexed already. Please Check out this index file '/mnt/vde/ming_totalRNASeq/20181025.A-siControl_Tal_1_R1Aligned.sortedByCoord.out.bam.bai'
'/mnt/vde/ming_totalRNASeq/20181025.A-siControl_Tal_2_R1Aligned.sortedByCoord.out.bam' seems to be indexed already. Please Check out this index file '/mnt/vde/ming_totalRNASeq/20181025.A-siControl_Tal_2_R1Aligned.sortedByCoord.out.bam.bai'
'/mnt/vde/ming_totalRNASeq/20181025.A-siControl_Tal_3_R1Aligned.sortedByCoord.out.bam' seems to be indexed already. Please Check out this index file '/mnt/vde/ming_totalRNASeq/20181025.A-siControl_Tal_3_R1Aligned.sortedByCoord.out.bam.bai'
'/mnt/vde/ming_totalRNASeq/20181025.A-siControl_DMSO_1_R1Aligned.sortedByCoord.out.bam' seems to be indexed already. Please Check out this index file '/mnt/vde/ming_totalRNASeq/20181025.A-siControl_DMSO_1_R1Aligned.sortedByCoord.out.bam.bai'
'/mnt/vde/ming_totalRNASeq/20181025.A-siControl_DMSO_2_R1Aligned.sortedByCoord.out.bam' seems to be indexed already. Please Check out this index file '/mnt/vde/ming_totalRNASeq/20181025.A-siControl_DMSO_2_R1Aligned.sortedByCoord.out.bam.bai'
'/mnt/vde/ming_totalRNASeq/20181025.A-siControl_DMSO_3_R1Aligned.sortedByCoord.out.bam' seems to be indexed already. Please Check out this index file '/mnt/vde/ming_totalRNASeq/20181025.A-siControl_DMSO_3_R1Aligned.sortedByCoord.out.bam.bai'

list index out of range
There is an exception in plot_with_eventsfile

**Comment by DMMDUZH** [comment] 2019-06-21 08:00
Hi,

I found the mistake that lead me to have the error reported above. It is my event file. Then I tried to look at the test data event file and found that the link that allows us to download the test data does not exist anymore. Could you please send me the event text file for me to check the format.

Best regards

Kapila

**Comment by DMMDUZH** [comment] 2019-06-21 15:14
Hi,

Everything is fine now and I got everything working now. 

Thanks anyway

Kapila

**Comment by anksi** [comment] 2020-03-03 12:13
Hi All,
Has anyone found the solution to the error mentioned above?
I am having the same error!

'A.bam' seems to be indexed already. Please Check out this index file 'A.bam.bai'

list index out of range
There is an exception in plot_with_coordinate

Thanks

**Comment by AmrR101** [comment] 2020-03-18 17:36
@ShiehShieh @bahramis I am getting the error below regarding "chr" in event but not in bam. I tried to get rid of chr in the rMATS output too but that causes other issues and no pdf is generated. Kindly advice.
##
Plotting read densities and MISO estimates along event...
  - Event: chr12:123973123:123974020:+@chr12:123988043:123988138:+@chr12:124004878:124004935:+
Setting up plot using dimensions:  [8.0, 7.0]
Using intron scale  1.0
Using exon scale  1.0
Reading sample label: ZNF664 Control-1 IncLevel: 1.00
Error retrieving files from chr12: invalid contig `chr12`
Are you sure chr12 appears in your BAM file?
Aborting plot...
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/rmats2sashimiplot-2.0.2-py2.7.egg/MISO/misopy/sashimi_plot/sashimi_plot.py", line 293, in <module>
    main()
  File "/usr/local/lib/python2.7/site-packages/rmats2sashimiplot-2.0.2-py2.7.egg/MISO/misopy/sashimi_plot/sashimi_plot.py", line 289, in main
    plot_label=plot_label)
  File "/usr/local/lib/python2.7/site-packages/rmats2sashimiplot-2.0.2-py2.7.egg/MISO/misopy/sashimi_plot/sashimi_plot.py", line 160, in plot_event
    plot_label=plot_label)
  File "/usr/local/lib/python2.7/site-packages/rmats2sashimiplot-2.0.2-py2.7.egg/MISO/misopy/sashimi_plot/plot_utils/plot_gene.py", line 838, in plot_density_from_file
    plot_title=plot_title)
  File "/usr/local/lib/python2.7/site-packages/rmats2sashimiplot-2.0.2-py2.7.egg/MISO/misopy/sashimi_plot/plot_utils/plot_gene.py", line 392, in plot_density
    junction_log_base=junction_log_base)
TypeError: 'AxesSubplot' object is not iterable
##
Thanks,
Amruta

**Comment by zcutts** [comment] 2020-04-10 18:47
I spent some time trying to figure out how to fix this issue for me, hope this helps someone in the future:

seems to be working for me using the solution from here https://support.bioconductor.org/p/78337/.  Problem appears to be with my BAM files, renaming from 1 to chr1 appears to solve the issue

`samtools view -H test.bam | sed -e 's/SN:\([0-9XY]\)/SN:chr\1/' -e 's/SN:MT/SN:chrM/' | samtools reheader - test.bam > test_chr.bam`


I was able to get some pdfs generated on a test case, will update if this doesn't work for my real data

**Comment by YingziZhang-github** [comment] 2020-05-07 15:42
Hi Zhijie @ShiehShieh ,
I met with the same above mentioned problem. It reported `'./WT_Aligned.sortedByCoord.out.bam' seems to be indexed already. Please C
heck out this index file './WT_Aligned.sortedByCoord.out.bam.bai'`. I saw you solved the problem by giving a new commit. But do you know how to solve this in my situation?
Besides, it reported `ImportError: No module named scipy`,`ImportError: No module named matplotlib`. Do you know how to deal with this?
Thank you in advance.

Best Regards,
Yingzi

**Comment by zcutts** [comment] 2020-05-07 16:02
Hi @YingziZhang-github when I run sashimiplot I get the same message 'seems to be indexed already', it seems to be more of a warning that an error, and I'm still able to generate plots.  

It seems that the issue is that [scipy](https://www.scipy.org/install.html) and [matplotlib](https://matplotlib.org/users/installing.html) aren't being loaded, perhaps if you try to pip install these packages it will work?  Looks like I'm using scipy version 1.2.3 and matplotlib version 1.5.3 with python 2.7.5

**Comment by YingziZhang-github** [comment] 2020-05-10 12:51
Hi, @zcutts Thank you for the reply. You are right. After install `scipy` and `matplotlib` and another package called `pysam`, everything works fine now. Thank you very much.

Best,
Yingzi

**Comment by YingziZhang-github** [comment] 2020-06-01 07:26
Hi Zhijie @ShiehShieh ,
I ran rmats2sashimiplot and I got a printed pdf but I received the following error report as well:
```
list index out of range
There is an exception in plot_with_eventsfile
```
Before the error, it had reported the steps of `reading settings from $.txt`, `saving plot to $pdf`, `Indexing... `and a command of `python <sashimi_plot.py> --plot-event "chr11 location" <sashimi_plot_settings.txt> --output-dir <Sashimi_plot>`.
Do you know whether the error matters? If so, how to solve it?
Thank you very much.

Yingzi

**Comment by EricKutschera** [comment] 2020-07-09 14:51
There are several different errors mentioned in this issue. Some have been addressed with recent code changes.

The "Are you sure chr10 appears in your BAM file?" issue was addressed in https://github.com/Xinglab/rmats2sashimiplot/pull/36

The error handling code was updated in https://github.com/Xinglab/rmats2sashimiplot/pull/38 so that a stack trace will be given along with "There is an exception in plot_with_coordinate". Also "'A.bam' seems to be indexed already." is not an error and the message has been updated.

Please open a new issue if needed after trying the latest source code

**Closed by EricKutschera** 2020-07-09 14:51 UTC

**Comment by celinelie** [comment] 2022-05-19 10:27
I'm having the same errors:
Reading sample label: Abi3bp Controls-1 IncLevel: 0.89
Error retrieving files from chr16: invalid reference `chr16`
Are you sure chr16 appears in your BAM file?
Aborting plot...
Traceback (most recent call last):
  File "/data/home/bt21020/.conda/envs/py.2.7/lib/python2.7/site-packages/MISO/misopy/sa
shimi_plot/sashimi_plot.py", line 293, in <module>
    main()
  File "/data/home/bt21020/.conda/envs/py.2.7/lib/python2.7/site-packages/MISO/misopy/sa
shimi_plot/sashimi_plot.py", line 289, in main
    plot_label=plot_label)
  File "/data/home/bt21020/.conda/envs/py.2.7/lib/python2.7/site-packages/MISO/misopy/sa
shimi_plot/sashimi_plot.py", line 160, in plot_event
    plot_label=plot_label)
  File "/data/home/bt21020/.conda/envs/py.2.7/lib/python2.7/site-packages/MISO/misopy/sa
shimi_plot/plot_utils/plot_gene.py", line 838, in plot_density_from_file
    plot_title=plot_title)
  File "/data/home/bt21020/.conda/envs/py.2.7/lib/python2.7/site-packages/MISO/misopy/sa
shimi_plot/plot_utils/plot_gene.py", line 392, in plot_density
    junction_log_base=junction_log_base)
TypeError: 'AxesSubplot' object is not iterable
mv: cannot stat ‘/data/scratch/bt21020/2022-05-16-sashimi/result/HGS2/test/Sashimi_plot/
chr16:56592604:56592681:+@chr16:56594462:56594536:+@chr16:56642489:56642560:+.pdf’: No s
uch file or directory

I'm using bam files from rmats output so does this mean I have to edit the bam files for the chr column? Please help thank you.

**Comment by EricKutschera** [comment] 2022-05-19 12:30
If you are using rmats2sashimiplot v2.0.4, the code should handle removing 'chr' from the events file if needed. If you can run from the latest source code on the master branch then there are also additional arguments that could help (--keep-event-chr-prefix, --remove-event-chr-prefix): https://github.com/Xinglab/rmats2sashimiplot/blob/fedd1bbe9eca37cee510393f294795eaa7e52eaf/src/rmats2sashimiplot/rmats2sashimiplot.py#L538

If that doesn't work, could you share the commandline you are using and also check your input files to see if they are using 'chr16' or just '16' as the name of the chromosome?

**Comment by celinelie** [comment] 2022-05-19 14:57
my input bam files do not have "chr" in the chromosome column. I tried running the command using bam files with "chr16" as the chromosome name and it gave me pdf files with empty plots.

Here's my the command line I ran:
rmats2sashimiplot --b1 test11_chr.bam,test12_chr.bam,test13_chr.bam,test14_chr.bam --b2 test21_chr.bam,test22_chr.bam,test23_chr.bam -o /result/HGS2/test -t SE -e test.SE.MATS.JC.txt --l1 Controls --l2 Treated --intron_s 5 --exon_s 1

I installed the package using bioconda and the latest version on it is v2.0.3

**Comment by EricKutschera** [comment] 2022-05-19 15:17
The latest version on bioconda is v2.0.4: https://anaconda.org/bioconda/rmats2sashimiplot

There may be a dependency conflict in your conda environment that prevented v2.0.4 from being installed. You should be able to install it in a new conda environment:
```
conda deactivate
conda create --prefix ./conda_env_v204
conda activate ./conda_env_v204
conda install -c conda-forge -c bioconda rmats2sashimiplot=2.0.4
```

With that conda environment you can also run the latest code:
```
git clone https://github.com/Xinglab/rmats2sashimiplot.git
cd rmats2sashimiplot
./2to3.sh
python ./src/rmats2sashimiplot/rmats2sashimiplot.py --help
```

**Comment by EricKutschera** [comment] 2022-05-19 19:49
The new arguments (--keep-event-chr-prefix, --remove-event-chr-prefix) are not in v2.0.4. They are only in the latest source code which does not have a release version yet

v2.0.4 adds logic to automatically handle 'chr' so you might not need the new argument if you use v2.0.4. If you run directly from the latest source code (described above with `git clone`) then you could try the new arguments
